// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRbuOspufVzLis-eodFuoZKy6c9D3Iv_o',
    appId: '1:589387746591:web:e8fff1d7aa762849c3b42a',
    messagingSenderId: '589387746591',
    projectId: 'dart-coach-app',
    authDomain: 'dart-coach-app.firebaseapp.com',
    storageBucket: 'dart-coach-app.firebasestorage.app',
    measurementId: 'G-J3701GSY5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsGmdZIvhKbPDxuXcQeIFpKiFNCOOzPtA',
    appId: '1:589387746591:android:b9c9463f4c4227cac3b42a',
    messagingSenderId: '589387746591',
    projectId: 'dart-coach-app',
    storageBucket: 'dart-coach-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA--THujS83dzq4LlIhgYv0MrmIMWLPlI',
    appId: '1:589387746591:ios:3af09e4f42b161b1c3b42a',
    messagingSenderId: '589387746591',
    projectId: 'dart-coach-app',
    storageBucket: 'dart-coach-app.firebasestorage.app',
    iosBundleId: 'com.example.dartCoachApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA--THujS83dzq4LlIhgYv0MrmIMWLPlI',
    appId: '1:589387746591:ios:3af09e4f42b161b1c3b42a',
    messagingSenderId: '589387746591',
    projectId: 'dart-coach-app',
    storageBucket: 'dart-coach-app.firebasestorage.app',
    iosBundleId: 'com.example.dartCoachApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRbuOspufVzLis-eodFuoZKy6c9D3Iv_o',
    appId: '1:589387746591:web:c91923083a5bd0a6c3b42a',
    messagingSenderId: '589387746591',
    projectId: 'dart-coach-app',
    authDomain: 'dart-coach-app.firebaseapp.com',
    storageBucket: 'dart-coach-app.firebasestorage.app',
    measurementId: 'G-ML1P1BXWNK',
  );
}
